# Day 1

## Q1

In [16]:
import numpy as np
# 1
my_array = np.random.rand(10)
# 2
print(my_array)
# 3 and 4
print(my_array.reshape(5,2))
my_array=my_array.reshape(5,2)
# 5 
print(my_array.sum())
# 6
print(my_array.mean())
# 7
print(np.max(my_array))
# 8
print(np.argmax(my_array))
# 9
print(np.argmin(my_array))
# 10
new_array = my_array[0:2,:]
print(new_array)

[0.2837263  0.98967915 0.60245045 0.91327982 0.85215042 0.54035838
 0.86543852 0.85902437 0.49158311 0.6389643 ]
[[0.2837263  0.98967915]
 [0.60245045 0.91327982]
 [0.85215042 0.54035838]
 [0.86543852 0.85902437]
 [0.49158311 0.6389643 ]]
7.036654830548256
0.7036654830548257
0.9896791492494231
1
0
[[0.2837263  0.98967915]
 [0.60245045 0.91327982]]


## Q2

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
# 1
print(np.intersect1d(a,b))
# 2
print(a[~np.in1d(a, b)])


[2 3 4 5]
[1]


## Q3

In [62]:
a = np.ones((4,4))
a[1:3,1:3] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Q4

In [66]:
file_name = 'files/scores.txt'
array = np.loadtxt(file_name,delimiter=',',ndmin=2)
array

array([[94., 88., 78., 97.],
       [92., 84., 80., 95.],
       [88., 40., 72., 88.],
       [83., 87., 45., 91.],
       [78., 77., 86., 83.]])

## Q5

# Part 2

# Q1

In [92]:
import pandas as pd
list_series = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
np_series = pd.Series(np.array(list_series))
df = pd.DataFrame()
df['Chars'] = list_series
df['nums']  = np_series
df

Chars nums
0      a    a
1      b    b
2      c    c
3      e    e
4      d    d
5      f    f
6      g    g
7      h    h
8      i    i
9      j    j
10     k    k
11     l    l
12     m    m
13     n    n
14     o    o
15     p    p
16     q    q
17     r    r
18     s    s
19     t    t
20     u    u
21     v    v
22     w    w
23     x    x
24     y    y
25     z    z

In [ ]:
df

# Q2

In [83]:
q2_series = pd.Series([2,4,6,8,10])
q2_series[q2_series > 5]

2     6
3     8
4    10
dtype: int64

## Q3

In [108]:
exam_data = {'Name': ['Anna', 'Dima', 'Alex', 'James', 'Emily', 'Tom', 'Matt',
'Laura', 'Kevin', 'Jonas'],
'Score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'Attempt': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'Qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
q3_df = pd.DataFrame(exam_data)
q3_df['lables'] = labels
# 1
print(q3_df.columns)
# 2
print(q3_df.dtypes)
# 3
q3_df.set_index('Name')

Index(['Name', 'Score', 'Attempt', 'Qualify', 'lables'], dtype='object')
Name        object
Score      float64
Attempt      int64
Qualify     object
lables      object
dtype: object


Score  Attempt Qualify lables
Name                                
Anna    12.5        1     yes      a
Dima     9.0        3      no      b
Alex    16.5        2     yes      c
James    NaN        3      no      d
Emily    9.0        2      no      e
Tom     20.0        3     yes      f
Matt    14.5        1     yes      g
Laura    NaN        1      no      h
Kevin    8.0        2      no      i
Jonas   19.0        1     yes      j

# Q4

In [119]:
# 1
q3_df['Attempt'].sum()
# 2
q3_df[q3_df['Score'] == q3_df['Score'].max()]
# 3
q3_df['Score'].mean()

13.5625

## Q5

In [136]:
# 1
q3_df.loc[q3_df['Name'] == 'James', 'Score'] = 11.5
# 2
q3_df.loc[q3_df['Name'] == 'James', 'Name'] = 'Sam'
# 3


In [ ]:
q

In [137]:
q3_df

Name  Score  Attempt Qualify lables
0   Anna   12.5        1     yes      a
1   Dima    9.0        3      no      b
2   Alex   16.5        2     yes      c
3    Sam   11.5        3      no      d
4  Emily    9.0        2      no      e
5    Tom   20.0        3     yes      f
6   Matt   14.5        1     yes      g
7  Laura    NaN        1      no      h
8  Kevin    8.0        2      no      i
9  Jonas   19.0        1     yes      j