# Day 1

## Q1

In [16]:
import numpy as np
# 1
my_array = np.random.rand(10)
# 2
print(my_array)
# 3 and 4
print(my_array.reshape(5,2))
my_array=my_array.reshape(5,2)
# 5 
print(my_array.sum())
# 6
print(my_array.mean())
# 7
print(np.max(my_array))
# 8
print(np.argmax(my_array))
# 9
print(np.argmin(my_array))
# 10
new_array = my_array[0:2,:]
print(new_array)

[0.2837263  0.98967915 0.60245045 0.91327982 0.85215042 0.54035838
 0.86543852 0.85902437 0.49158311 0.6389643 ]
[[0.2837263  0.98967915]
 [0.60245045 0.91327982]
 [0.85215042 0.54035838]
 [0.86543852 0.85902437]
 [0.49158311 0.6389643 ]]
7.036654830548256
0.7036654830548257
0.9896791492494231
1
0
[[0.2837263  0.98967915]
 [0.60245045 0.91327982]]


## Q2

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
# 1
print(np.intersect1d(a,b))
# 2
print(a[~np.in1d(a, b)])


[2 3 4 5]
[1]


## Q3

In [62]:
a = np.ones((4,4))
a[1:3,1:3] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Q4

In [66]:
file_name = 'files/scores.txt'
array = np.loadtxt(file_name,delimiter=',',ndmin=2)
array

array([[94., 88., 78., 97.],
       [92., 84., 80., 95.],
       [88., 40., 72., 88.],
       [83., 87., 45., 91.],
       [78., 77., 86., 83.]])

## Q5